services:
  github-runner:
    deploy:
      replicas: ${RUNNER_REPLICAS:-1}
      resources:
        limits:
          cpus: "${RUNNER_CPU_LIMIT:-0}"
          memory: "${RUNNER_MEM_LIMIT:-0}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GITHUB_ORG: ${GITHUB_ORG:-NoMercy-Entertainment}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,Linux,X64}
      RUNNER_GROUP: ${RUNNER_GROUP:-}
    tmpfs:
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
